export const AuthActions = {
  SET_TOKENS: "AUTH/SET_TOKENS",
  SET_ACCESS_TOKEN: "AUTH/SET_ACCESS_TOKEN",
  SET_REFRESH_TOKEN: "AUTH/SET_REFRESH_TOKEN",
  COMPLETE_LOGIN: "AUTH/COMPLETE_LOGIN",
  CLEAR_TOKENS: "AUTH/CLEAR_TOKENS",
};
