export const PlacesActions = {
  INFO: "PLACE/INFO",
  UPDATE_FEED: "PLACE/UPDATE_FEED",
  UPDATE_PEOPLE: "PLACE/UPDATE_PEOPLE",
  TRANSITION_HEADER_COLLAPSE: "PLACE/TRANSITION_HEADER_COLLAPSE",
  TRANSITION_HEADER_EXPAND: "PLACE/TRANSITION_HEADER_EXPAND",
  TRANSITION_HIERARCHY_COLLAPSE: "PLACE/TRANSITION_HIERARCHY_COLLAPSE",
  TRANSITION_HIERARCHY_EXPAND: "PLACE/TRANSITION_HIERARCHY_EXPAND",
  UPDATE_DISPLAY_SCREEN: "PLACE/UPDATE_DISPLAY_SCREEN",
  NAV_TOGO_PLACE_SCREEN_START: "HUB/NAV_TOGO_PLACE_SCREEN_START",
  NAV_TOGO_PLACE_SCREEN_END: "HUB/NAV_TOGO_PLACE_SCREEN_END",
};
