export const PlacesActions = {
  INFO: "PLACE/INFO",
  UPDATE_FEED: "PLACE/UPDATE_FEED",
  UPDATE_PEOPLE: "PLACE/UPDATE_PEOPLE",
  TRANSITION_HEADER_COLLAPSE: "PLACE/TRANSITION_HEADER_COLLAPSE",
  TRANSITION_HEADER_EXPAND: "PLACE/TRANSITION_HEADER_EXPAND",
};
