export const PlacesActions = {
  UPDATE_CURRENT_PLACE: "PLACE/UPDATE_CURRENT_PLACE",
  UPDATE_FEED: "PLACE/UPDATE_FEED",
  UPDATE_PEOPLE: "PLACE/UPDATE_PEOPLE",
  TRANSITION_HEADER_COLLAPSE: "PLACE/TRANSITION_HEADER_COLLAPSE",
  TRANSITION_HEADER_EXPAND: "PLACE/TRANSITION_HEADER_EXPAND",
  HEADER_TITLE_VISIBLE: "PLACE/HEADER_TITLE_VISIBLE",
  HEADER_TITLE_HIDDEN: "PLACE/HEADER_TITLE_HIDDEN",
  UPDATE_DISPLAY_SCREEN: "PLACE/UPDATE_DISPLAY_SCREEN",
  NAV_TOGO_PLACE_SCREEN_START: "HUB/NAV_TOGO_PLACE_SCREEN_START",
  NAV_TOGO_PLACE_SCREEN_END: "HUB/NAV_TOGO_PLACE_SCREEN_END",
};
