export const userConstants = {
  REGISTER_REQUEST: "USER/REGISTER_REQUEST",
  REGISTER_SUCCESS: "USER/REGISTER_SUCCESS",
  REGISTER_FAILURE: "USER/REGISTER_FAILURE",

  LOGIN_REQUEST: "USER/LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER/LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER/LOGIN_FAILURE",

  LOGOUT: "USER/LOGOUT",

  GETALL_REQUEST: "USER/GETALL_REQUEST",
  GETALL_SUCCESS: "USER/GETALL_SUCCESS",
  GETALL_FAILURE: "USER/GETALL_FAILURE",

  DELETE_REQUEST: "USER/DELETE_REQUEST",
  DELETE_SUCCESS: "USER/DELETE_SUCCESS",
  DELETE_FAILURE: "USER/DELETE_FAILURE",
};
